### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [jxp/phonegap-desktop#3]
Hi, Jonathan,

Nice work!

I was wondering what license you were planning to use for this.  The same Apache License as PhoneGap itself?

**Comment by jxp** [comment]
I have added Apache v2 license to the project now.
I'm expecting the project to be used by developers only but would be interested to hear if you have other plans.

**Comment by ghost** [comment]
Thanks! What I have (vaguely) in mind is something akin to Scratch 
http://scratch.mit.edu

perhaps based on Google Blockly 

http://code.google.com/p/blockly/?redir=1 

The use case for PhoneGap desktop here would be a desktop design and build system that would let the users create and test their apps without deploying to a device.
