### ISSUE TITLE
Ripple Emulator

### ISSUE THREAD

**Issue by stdavis** [jxp/phonegap-desktop#4]
How does this relate to the ripple emulator? Is it intended to be used in place of or along side ripple?

**Comment by jxp** [comment]
This project is intended as an alternative to Ripple
Ripple is a really nice UI to allow running a PhoneGap project in a browser and you can interactively simulate phone features.

However I found Ripple had a few limitations.
1. Ripple is Chrome only. What if you are developing for Windows Phone or iOS. Wouldn't IE9 or Safari be more suitable desktop browsers to use?
2. Ripple can't support plugins. A lot of PhoneGap functionality is extended by the use of plugins. 
3. You can't use a known set of data with Ripple. If you have certain scenarios you know you want to test it would be helpful to have some sort of "test script".

PhoneGap desktop attempts to address all of these issues I had with Ripple;
1. It is browser independant and has not external depencies
2. It is easily extensible to support plugins
3. Test data comes from a file and multiple files can be used for different scenarios.

RIpple is a great tool and may be what you need, PhoneGap Desktop is an alternative solution to the same problem. (you may also be interested in PhoneGap Proxy)

**Comment by stdavis** [comment]
Interesting. I will definitely check this out. Thanks!

**Comment by perqa** [comment]
@jxp: Very good explanation. This is the text I was missing in the ReadMe section! I suggest you copy it there as well.
