### ISSUE TITLE
Phonegap 2.2: navigator network interface has changed

### ISSUE THREAD

**Issue by samikrc** [jxp/phonegap-desktop#8]
I don't know what version of the api you are currently following, but Phonegap 2.2 api has changed the JS interfaces for the connection states. They used to be navigator.network connection, now they are navigator.connection.
See here: http://docs.phonegap.com/en/2.2.0/cordova_connection_connection.md.html#Connection
Requesting an update.
Thanks.

**Comment by jxp** [comment]
Updated PhoneGap Desktop to support both versions of the API. Will remove navigator.network at some future data.

**Comment by samikrc** [comment]
Thanks.
