### ISSUE TITLE
Navigation fix causes crash at line 571.

### ISSUE THREAD

**Issue by robvon** [jxp/phonegap-desktop#9]
You have chosen to "leave previous" however since it doesn't exist, your method setDynamicProperty just crashes.

Remove line 571 please

//phonegapdesktop.internal.setDynamicProperty(navigator.connection, "connection", "type");

**Comment by jxp** [comment]
Sorry about that. I pushed to git before fully checking it. I have now amended the change so that both versions of the API work correctly. (And its fully checked now)
